package lishui.lib.router.processor.utils;

/**
 * author : linlishui
 * time   : 2021/10/15
 * desc   : 配置常量
 */
public class Configs {

    private Configs() {
    }

    // Generate
    public static final String PROJECT = "Router";
    public static final String SEPARATOR = "$$";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY ROUTER.";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String NAME_OF_ROOT = PROJECT + SEPARATOR + "Root";
    public static final String NAME_OF_GROUP = PROJECT + SEPARATOR + "Group" + SEPARATOR;
    public static final String PACKAGE_OF_GENERATE_FILE = "lishui.lib.router.routes";

    // System interface
    public static final String ACTIVITY = "android.app.Activity";
    public static final String SERVICE = "android.app.Service";

    // Custom interface
    private static final String API_PACKAGE = "lishui.lib.router.api";
    private static final String TEMPLATE_PACKAGE = ".template";
    public static final String IPROVIDER = API_PACKAGE + TEMPLATE_PACKAGE + ".IProvider";
    public static final String ITROUTE_ROOT = API_PACKAGE + TEMPLATE_PACKAGE + ".IRouteRoot";
    public static final String IROUTE_GROUP = API_PACKAGE + TEMPLATE_PACKAGE + ".IRouteGroup";

    // Annotation type
    private static final String ANNOTATION_PACKAGE = "lishui.lib.router.annotation";
    public static final String ANNOTATION_TYPE_ROUTE = ANNOTATION_PACKAGE + ".Route";

    // Log
    public static final String PREFIX_OF_LOGGER = "RouterProcessorLog: ";
    public static final String NO_MODULE_NAME_TIPS = "These no module name, at 'build.gradle', like :\n" +
            "android {\n" +
            "    defaultConfig {\n" +
            "        ...\n" +
            "        javaCompileOptions {\n" +
            "            annotationProcessorOptions {\n" +
            "                arguments = [ROUTER_MODULE_NAME: project.getName()]\n" +
            "            }\n" +
            "        }\n" +
            "    }\n" +
            "}\n";

    // Options of processor
    public static final String OPTION_MODULE_NAME = "ROUTER_MODULE_NAME";
}
